#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "Usage: $0 <tag> <checksums-file> <output-file>" >&2
  exit 2
fi

tag="$1"
checksums_file="$2"
output_file="$3"

if [[ ! "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Homebrew formula generation requires a stable SemVer tag." >&2
  exit 1
fi
if [[ ! -f "$checksums_file" ]]; then
  echo "Checksums file does not exist: $checksums_file" >&2
  exit 1
fi

version="${tag#v}"

archive_digest() {
  local target="$1"
  local archive="forecast-ledger_${version}_${target}.tar.gz"
  local digest
  digest="$(awk -v name="$archive" '$2 == name { print $1 }' "$checksums_file")"
  if [[ ! "$digest" =~ ^[0-9a-f]{64}$ ]]; then
    echo "Published digest is missing or invalid for $archive." >&2
    exit 1
  fi
  printf '%s' "$digest"
}

darwin_arm64_sha="$(archive_digest darwin_arm64)"
darwin_amd64_sha="$(archive_digest darwin_x86_64)"
linux_arm64_sha="$(archive_digest linux_arm64)"
linux_amd64_sha="$(archive_digest linux_x86_64)"

mkdir -p "$(dirname "$output_file")"
cat >"$output_file" <<EOF
# This file was generated by the forecast-ledger release workflow. DO NOT EDIT.
class ForecastLedger < Formula
  desc "Create and verify portable forecast evidence"
  homepage "https://chaoscondensate.com/"
  version "$version"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chaoscondensate/cli/releases/download/$tag/forecast-ledger_${version}_darwin_arm64.tar.gz"
      sha256 "$darwin_arm64_sha"
    else
      url "https://github.com/chaoscondensate/cli/releases/download/$tag/forecast-ledger_${version}_darwin_x86_64.tar.gz"
      sha256 "$darwin_amd64_sha"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaoscondensate/cli/releases/download/$tag/forecast-ledger_${version}_linux_arm64.tar.gz"
      sha256 "$linux_arm64_sha"
    else
      url "https://github.com/chaoscondensate/cli/releases/download/$tag/forecast-ledger_${version}_linux_x86_64.tar.gz"
      sha256 "$linux_amd64_sha"
    end
  end

  def install
    bin.install "forecast-ledger"
    if OS.mac?
      system "/usr/bin/xattr", "-cr", bin/"forecast-ledger"
      system "/usr/bin/codesign", "--force", "--sign", "-", bin/"forecast-ledger"
    end
    generate_completions_from_executable(bin/"forecast-ledger", "completion")
  end

  test do
    output = shell_output("#{bin}/forecast-ledger version --json")
    assert_match "\"version\":\"#{version}\"", output
  end
end
EOF

ruby -c "$output_file"
